### ISSUE TITLE
IE11 error

### ISSUE THREAD

**Issue by jberney** [oaf-project/oaf-react-router#16]
Hello!

I am trying to use `oaf-react-router` in my project. However, when I import wrapHistory from oaf-react-router:
```import { wrapHistory } from 'oaf-react-router';```

I get a syntax error in IE11. The syntax error is on a line from `oaf-side-effects`:

```
exports.elementFromHash = (hash) => {
```

I believe the error occurs because the fat arrow syntax is not supported in IE11.

I looked at the build process for the oaf projects, and it appears that this may have been an intentional choice to target es6 rather than es5:

```
{
  "compilerOptions": {
    "target": "es6",
```

Would you consider PRs to each of the oaf libraries that changes the target to es5 instead, so that the build output of this library can be compatible with IE11? If you want to keep it targetting es6, do you have recommendations for how to include these libraries such that the resulting project can be viewed in IE11?

Thanks!

**Comment by danielnixon** [comment]
Thanks for the bug report! I run the TypeScript output through Babel which I think is why I missed this.

PRs very welcome, otherwise I'll fix this myself soon. 👍

**Comment by danielnixon** [comment]
I've just published oaf-side-effects, oaf-routing and oaf-react-router packages targeting es5. I'll leave this issue open for now.

**Comment by jberney** [comment]
Thanks for the quick reply @danielnixon! Everything appears to work now in IE11!

I did notice that there are still a couple of fat arrows in `oaf-routing/dist/routing.js`:
* Line 15:
```exports.handleFirstPageLoad = (settings, location, hash) => __awaiter(this, void 0, void 0, function* () {```
* Line 20:
```        setTimeout(() => {```

I'm not sure why `tsc` isn't transpiling these, but I haven't yet noticed it to be an issue.

Thanks again!

**Comment by danielnixon** [comment]
That's interesting. Probably due to async/await. I'll remove the async/await soon.
