### ISSUE TITLE
disabling scroll-to-top for certain routes, tabs, carousel, etc..

### ISSUE THREAD

**Issue by BBaysinger** [oaf-project/oaf-react-router#17]
There doesn't appear to be anything in the documentation about disabling scroll-to-top for certain routes, like what would be necessary for tabs, or a carousel. Is that a feature that exists here? If so, it should be in the documentation. I might have to pass up using this library due to the necessity of this feature.

**Comment by danielnixon** [comment]
Return false from `shouldHandleAction`

**Comment by BBaysinger** [comment]
Perfect!! Absolutely works! Thanks so much for this utility!
