### ISSUE TITLE
put together example/demo

### ISSUE THREAD

**Issue by danielnixon** [oaf-project/oaf-react-router#2]

**Comment by lucascassilha** [comment]
Hi there!
I developed an example for your library if you wish to [take a look](https://github.com/lucascassilha/oaf-react-router-example)

**Comment by danielnixon** [comment]
The unit tests (https://github.com/oaf-project/oaf-react-router/blob/master/src/index.test.tsx) now contain usage examples that are good enough. They use jsx, they render react elements, they demonstrate how to use the latest hotness (`createBrowserRouter`). Closing this.
