### ISSUE TITLE
React Router v6 support

### ISSUE THREAD

**Issue by danielnixon** [oaf-project/oaf-react-router#210]
https://reacttraining.com/blog/react-router-v6-pre/

**Comment by danielnixon** [comment]
https://github.com/oaf-project/oaf-react-router/pull/122

**Comment by Kamahl19** [comment]
@danielnixon Hey do you have any ETA on this? Thanks!

**Comment by danielnixon** [comment]
No current plans. PRs welcome.

**Comment by danielnixon** [comment]
https://github.com/remix-run/react-router/blob/main/docs/upgrading/v5.md

**Comment by danielnixon** [comment]
I've just published a new major version (3.0.0) targeting history@5 (the version used by react-router@6)

**Comment by Kamahl19** [comment]
@danielnixon Thanks! Does that mean v3 is fully compatible with React router v6?

**Comment by janaagaard75** [comment]
Any code examples on how to use oaf-react-router with React Router 6? The [basic usage code snippet](https://github.com/oaf-project/oaf-react-router#basic-usage) isn't compatible with React Router 6.

**Comment by danielnixon** [comment]
You will need to use the `HistoryRouter` from `react-router-dom`:

```ts
/**
 * A `<Router>` that accepts a pre-instantiated history object. It's important
 * to note that using your own history object is highly discouraged and may add
 * two versions of the history library to your bundles unless you use the same
 * version of the history library that React Router uses internally.
 */
function HistoryRouter(_ref3) {
```

Something like this should work, though I haven't tested:

```ts
// ts
import { createBrowserHistory } from "history";
import { wrapHistory } from "oaf-react-router";

const history = createBrowserHistory(); // or createHashHistory()
wrapHistory(history);

// tsx
import { unstable_HistoryRouter as HistoryRouter } from "react-router-dom";

<HistoryRouter history={history}>
```

As always, contributions welcome.

**Comment by janaagaard75** [comment]
Thanks a lot for the code snippet, @danielnixon. It works. :)

(What I was missing was the `as HistoryRouter` in the import. It is, apparently, not accepted to write `< unstable_HistoryRouter>...</unstable_HistoryRouter>` in the JSX code.

**Comment by danielnixon** [comment]
I've updated the readme, I think we can close this issue.
