### ISSUE TITLE
How about BrowserRouter basename props replace

### ISSUE THREAD

**Issue by wildfrontend** [oaf-project/oaf-react-router#341]
how can i set `basename` attribute? in `oaf-react-router` Router

**Comment by danielnixon** [comment]
Hi @wildfrontend. Using the latest versions of react-router and oaf-react-router, you would specify basename the normal way, like this:

https://reactrouter.com/ru/main/routers/create-browser-router#basename


```typescript
const router = createBrowserRouter(routes, {
  basename: "/app",
});

wrapRouter(router);
```
