### ISSUE TITLE
Prevent scroll/focus on query param changes

### ISSUE THREAD

**Issue by WoodburyShortridge** [oaf-project/oaf-react-router#43]
Looking to prevent scrolling/focusing to top on url query param change. This is a typical use-case for filtering/searching etc. where a both a screen-reader user and visual user's focus should remain on active element. 

Current behavior: Focus/scroll to to when query param changes
Preferred behavior: Focus/scroll remain same when query param changes

Is there a way to blacklist certain pathname patterns?

**Comment by danielnixon** [comment]
Check out https://github.com/oaf-project/oaf-react-router/issues/17

**Comment by WoodburyShortridge** [comment]
Thanks @danielnixon closing.
